import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedFirebaseData() async {
  final firestore = FirebaseFirestore.instance;
  
  // 1. Seed Banners
  final banners = [
    {
      'title': "Winter Collection '24",
      'imageUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuChS8WqKGtV-g3Wu9KrbzLT51FYRso_SOsuOBRilnbjBQNRUO5wPbUu550b0UK0VbNcq1qPkk2rCFg6uX5mGoWKvYAfBBKb23WBBIvt_yBe2aoIC7w_8oyboVmFRacgBmREyTQI3zJyR3hZKfnIwsi1Xbp23vwsZ93492B7QeXbb20BP33pWgP6JThm9mLPpUhmUftUfQ84r9tXW9bQVDh-LX29UlrMLCe-jWJpg-roQ_wpopnr_Qnd2_-gKdpYs59u7lB1ENuaC_w',
      'actionLabel': 'Shop Now',
      'actionRoute': '/shop',
      'sortOrder': 1,
      'isActive': true,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'title': 'Minimalist Basics',
      'imageUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqT6dafN_K2rJnNg2p3V4cgBg2Y2GW728SP2abMko7WZmmxI23_PHK2GuCXBpvGlAQ-rjpuryH7KBCwyIDZrlvBU7nYNnwTpf4fo9Vm-9skdFGBQeZKuzWLuCYGnVIbIzTRzPynRS3FTgnVHRPGYRqy0RBLYdAvvbq5Cp43du1dWK2bTKSDTQ30DjRd9voV0kf72uICvmJOzDfqJm8j4znGo6EjhiS5KsKhibtlIu_SA3StFeqTyOB6SrzpX5u4YPZr_Bi14N1bC8',
      'actionLabel': 'Explore',
      'actionRoute': '/shop',
      'sortOrder': 2,
      'isActive': true,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'title': 'Premium Leather',
      'imageUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEdNSpTBeqSi0X15xM1g3eFnoeSVD-up05dxEQhzZIxs65FduSXk7oFRKXty3oWxLigyAYN0wWozQzG6X93ioHog9R4iGnjqpr_Gn0rjDn_1302smBqwqNgKOwgKTLRpxdWJep0YgnId0fUcsVgfVSqi7Unx4gypefnY34weMGYMNGbNRrNKryeG2mRUozCKKYeAFC4Pbg_yIashvP6zlh7w4LyOPx7fpItg1kDW04p26NGPvWXo-aBLdgOfUr653F0RwdiSgAqPY',
      'actionLabel': 'View Bags',
      'actionRoute': '/shop',
      'sortOrder': 3,
      'isActive': true,
      'createdAt': FieldValue.serverTimestamp(),
    },
  ];

  for (final b in banners) {
    await firestore.collection('banners').add(b);
  }

  // 2. Seed Products
  final products = [
    {
      'name': 'Silk Blend Blazer',
      'brand': 'LUXR',
      'description': 'Premium silk blend blazer for elegant evenings.',
      'category': 'Outerwear',
      'searchIndex': ['silk', 'blend', 'blazer', 'luxr', 'outerwear'],
      'tags': ['premium', 'formal'],
      'price': 1050.0,
      'discountPct': 20,
      'finalPrice': 840.0,
      'imageUrls': ['https://lh3.googleusercontent.com/aida-public/AB6AXuCJk9i0cjkfKlHFG80NUSbrND9CEjFfo_svVVgPSUHGYiymVqWrbL5Ps_xUgvwOvGwtVzE993VJqd62_Dsw0PoiXr9eKOg-HNstfzubaFGyuHZdn8JMWpYBPWkXc00CkmP55_c_o3ktZ_jGnUCkfhpR48CAfIj1vSycAwXf9eoyI-YURY-B00maun2bLANMr2AtVBpHHUvtq-avVAV3PuBSm_EOx7ZLS2I5K7C4vo_pKsmAZDcuiKdh7jQp1o3cS3H0TShoJIiuNxM'],
      'thumbnailUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJk9i0cjkfKlHFG80NUSbrND9CEjFfo_svVVgPSUHGYiymVqWrbL5Ps_xUgvwOvGwtVzE993VJqd62_Dsw0PoiXr9eKOg-HNstfzubaFGyuHZdn8JMWpYBPWkXc00CkmP55_c_o3ktZ_jGnUCkfhpR48CAfIj1vSycAwXf9eoyI-YURY-B00maun2bLANMr2AtVBpHHUvtq-avVAV3PuBSm_EOx7ZLS2I5K7C4vo_pKsmAZDcuiKdh7jQp1o3cS3H0TShoJIiuNxM',
      'inventory': {'S': 5, 'M': 10, 'L': 5},
      'totalStock': 20,
      'lowStockThreshold': 5,
      'colors': [{'name': 'Black', 'hexCode': '#000000'}],
      'isActive': true,
      'isFeatured': true,
      'isNewArrival': false,
      'isLimitedEdition': false,
      'avgRating': 4.8,
      'reviewCount': 12,
      'soldCount': 45,
      'viewCount': 100,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Essential Tee',
      'brand': 'LUXR',
      'description': 'Minimalist black t-shirt made with heavy cotton.',
      'category': 'Shirts',
      'searchIndex': ['essential', 'tee', 'luxr', 'shirts', 'black'],
      'tags': ['basics', 'cotton'],
      'price': 125.0,
      'discountPct': 0,
      'finalPrice': 125.0,
      'imageUrls': ['https://lh3.googleusercontent.com/aida-public/AB6AXuBqT6dafN_K2rJnNg2p3V4cgBg2Y2GW728SP2abMko7WZmmxI23_PHK2GuCXBpvGlAQ-rjpuryH7KBCwyIDZrlvBU7nYNnwTpf4fo9Vm-9skdFGBQeZKuzWLuCYGnVIbIzTRzPynRS3FTgnVHRPGYRqy0RBLYdAvvbq5Cp43du1dWK2bTKSDTQ30DjRd9voV0kf72uICvmJOzDfqJm8j4znGo6EjhiS5KsKhibtlIu_SA3StFeqTyOB6SrzpX5u4YPZr_Bi14N1bC8'],
      'thumbnailUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqT6dafN_K2rJnNg2p3V4cgBg2Y2GW728SP2abMko7WZmmxI23_PHK2GuCXBpvGlAQ-rjpuryH7KBCwyIDZrlvBU7nYNnwTpf4fo9Vm-9skdFGBQeZKuzWLuCYGnVIbIzTRzPynRS3FTgnVHRPGYRqy0RBLYdAvvbq5Cp43du1dWK2bTKSDTQ30DjRd9voV0kf72uICvmJOzDfqJm8j4znGo6EjhiS5KsKhibtlIu_SA3StFeqTyOB6SrzpX5u4YPZr_Bi14N1bC8',
      'inventory': {'M': 50, 'L': 50},
      'totalStock': 100,
      'lowStockThreshold': 10,
      'colors': [{'name': 'Black', 'hexCode': '#000000'}],
      'isActive': true,
      'isFeatured': true,
      'isNewArrival': false,
      'isLimitedEdition': false,
      'avgRating': 4.5,
      'reviewCount': 50,
      'soldCount': 200,
      'viewCount': 300,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Leather Carry-all',
      'brand': 'LUXR',
      'description': 'Elegant leather bag for all occasions.',
      'category': 'Accessories',
      'searchIndex': ['leather', 'carry-all', 'luxr', 'bag', 'accessories'],
      'tags': ['bags', 'leather'],
      'price': 1411.0,
      'discountPct': 15,
      'finalPrice': 1200.0,
      'imageUrls': ['https://lh3.googleusercontent.com/aida-public/AB6AXuBEdNSpTBeqSi0X15xM1g3eFnoeSVD-up05dxEQhzZIxs65FduSXk7oFRKXty3oWxLigyAYN0wWozQzG6X93ioHog9R4iGnjqpr_Gn0rjDn_1302smBqwqNgKOwgKTLRpxdWJep0YgnId0fUcsVgfVSqi7Unx4gypefnY34weMGYMNGbNRrNKryeG2mRUozCKKYeAFC4Pbg_yIashvP6zlh7w4LyOPx7fpItg1kDW04p26NGPvWXo-aBLdgOfUr653F0RwdiSgAqPY'],
      'thumbnailUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEdNSpTBeqSi0X15xM1g3eFnoeSVD-up05dxEQhzZIxs65FduSXk7oFRKXty3oWxLigyAYN0wWozQzG6X93ioHog9R4iGnjqpr_Gn0rjDn_1302smBqwqNgKOwgKTLRpxdWJep0YgnId0fUcsVgfVSqi7Unx4gypefnY34weMGYMNGbNRrNKryeG2mRUozCKKYeAFC4Pbg_yIashvP6zlh7w4LyOPx7fpItg1kDW04p26NGPvWXo-aBLdgOfUr653F0RwdiSgAqPY',
      'inventory': {'One Size': 10},
      'totalStock': 10,
      'lowStockThreshold': 2,
      'colors': [{'name': 'Brown', 'hexCode': '#8b4513'}],
      'isActive': true,
      'isFeatured': true,
      'isNewArrival': false,
      'isLimitedEdition': false,
      'avgRating': 5.0,
      'reviewCount': 8,
      'soldCount': 10,
      'viewCount': 80,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Tech Parka',
      'brand': 'LUXR',
      'description': 'Modern streetwear look with advanced tech fabric.',
      'category': 'Outerwear',
      'searchIndex': ['tech', 'parka', 'luxr', 'outerwear', 'streetwear'],
      'tags': ['tech', 'winter'],
      'price': 450.0,
      'discountPct': 0,
      'finalPrice': 450.0,
      'imageUrls': ['https://lh3.googleusercontent.com/aida-public/AB6AXuA6whiWX7rJ280f90qnT8ngmRULcTdU3VldU5eLJxGVsTPKqGvBVWwHlue4cJR9BSvGvD7awf5ldqLq2AJj4m0csZA1uJ-RskX5pUq1ED_j3TN0rdFRSWbf_P5VUMM5OVk9LiYl9g6FGt4qvfc0B4qLpom_XEUdWZ6wSaW9TByJ8Fu0CzegrXgvg-DBXvktLU_Yz8qKY1dHAzgFgcnh5cwVqrh0DEZOXZNbNHMYtpZGGavx7Pbtvin6Ho6OkwrA0QIy45RWQjcEwgo'],
      'thumbnailUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuA6whiWX7rJ280f90qnT8ngmRULcTdU3VldU5eLJxGVsTPKqGvBVWwHlue4cJR9BSvGvD7awf5ldqLq2AJj4m0csZA1uJ-RskX5pUq1ED_j3TN0rdFRSWbf_P5VUMM5OVk9LiYl9g6FGt4qvfc0B4qLpom_XEUdWZ6wSaW9TByJ8Fu0CzegrXgvg-DBXvktLU_Yz8qKY1dHAzgFgcnh5cwVqrh0DEZOXZNbNHMYtpZGGavx7Pbtvin6Ho6OkwrA0QIy45RWQjcEwgo',
      'inventory': {'M': 10, 'L': 10},
      'totalStock': 20,
      'lowStockThreshold': 3,
      'colors': [{'name': 'Grey', 'hexCode': '#808080'}],
      'isActive': true,
      'isFeatured': false,
      'isNewArrival': true,
      'isLimitedEdition': false,
      'avgRating': 4.7,
      'reviewCount': 5,
      'soldCount': 20,
      'viewCount': 150,
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Luxe Fleece',
      'brand': 'LUXR',
      'description': 'Oversized designer hoodie for extreme comfort.',
      'category': 'Hoodies',
      'searchIndex': ['luxe', 'fleece', 'luxr', 'hoodies', 'comfort'],
      'tags': ['oversized', 'fleece'],
      'price': 290.0,
      'discountPct': 0,
      'finalPrice': 290.0,
      'imageUrls': ['https://lh3.googleusercontent.com/aida-public/AB6AXuAJSNYmA0Bo7vi5rW3vS_XPa8Xv28nKBB86iMxFSMgAkcpN4h6hVZyNqd5PuXr_Wk1ONQ36xcitcPtaLjxImTv8d0Vzbfc0Q1JVEFzilmZ9VvTkU_LB0gZ00YzvOHQc9UbADkQgCbVKoHFSVOHxhpzyfk8aPFVW2LLUofPuKH_1wV9LLAXSR1eqyCSf9nEQDfkTGI9_31mARRisugdDdG1XG1fK9vI26ssR6nGiX4DCGrCOXOHaXLal_AiPwQ2KPLeZ-dlXg38r8qA'],
      'thumbnailUrl': 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJSNYmA0Bo7vi5rW3vS_XPa8Xv28nKBB86iMxFSMgAkcpN4h6hVZyNqd5PuXr_Wk1ONQ36xcitcPtaLjxImTv8d0Vzbfc0Q1JVEFzilmZ9VvTkU_LB0gZ00YzvOHQc9UbADkQgCbVKoHFSVOHxhpzyfk8aPFVW2LLUofPuKH_1wV9LLAXSR1eqyCSf9nEQDfkTGI9_31mARRisugdDdG1XG1fK9vI26ssR6nGiX4DCGrCOXOHaXLal_AiPwQ2KPLeZ-dlXg38r8qA',
      'inventory': {'S': 5, 'M': 5},
      'totalStock': 10,
      'lowStockThreshold': 2,
      'colors': [{'name': 'Black', 'hexCode': '#000000'}],
      'isActive': true,
      'isFeatured': true,
      'isNewArrival': true,
      'isLimitedEdition': true,
      'avgRating': 4.9,
      'reviewCount': 22,
      'soldCount': 85,
      'viewCount': 400,
      'createdAt': FieldValue.serverTimestamp(),
    }
  ];

  for (final p in products) {
    await firestore.collection('products').add(p);
  }
}
