/// ══════════════════════════════════════════════════════════
/// COLLECTION 1: /users/{uid}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: Stores all user profiles (admin + customer)
/// DOCUMENT ID: Firebase Auth UID
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   // ── Identity ──────────────────────────────────────
///   "uid":           String,   // = document ID
///   "email":         String,   // lowercase, trimmed
///   "displayName":   String,   // min 2 chars
///   "photoUrl":      String?,  // Firebase Storage URL
///   "role":          String,   // ENUM: 'admin' | 'customer'
///   "emailVerified": bool,     // synced from Firebase Auth
///
///   // ── Session ───────────────────────────────────────
///   "fcmToken":      String?,  // updated on every login
///   "createdAt":     Timestamp,// FieldValue.serverTimestamp
///   "lastLoginAt":   Timestamp,// updated on every login
///
///   // ── Commerce ──────────────────────────────────────
///   "totalOrders":   int,      // incremented via transaction
///   "totalSpent":    double,   // incremented via transaction
///   "eliteStatus":   String,   // COMPUTED: see rules below
///                              // 'BRONZE'|'SILVER'|'GOLD'
///                              // |'PLATINUM'
///   "wishlistCount": int,      // incremented/decremented
///
///   // ── Addresses (embedded array, max 5) ─────────────
///   "addresses": [
///     {
///       "addressId":  String,  // UUID v4
///       "label":      String,  // 'Home'|'Office'|'Other'
///       "fullName":   String,  // recipient name
///       "phone":      String,  // with country code
///       "street":     String,
///       "city":       String,
///       "state":      String,
///       "zipCode":    String,
///       "country":    String,  // ISO 3166-1 alpha-2
///       "isDefault":  bool     // only 1 can be true
///     }
///   ],
///
///   // ── Notification Preferences ───────────────────────
///   "notificationPrefs": {
///     "orderUpdates":  bool,   // default: true
///     "promotions":    bool,   // default: true
///     "newArrivals":   bool    // default: false
///   }
/// }
///
/// ELITE STATUS RULES (computed on every order completion):
///   totalOrders 0-4   → 'BRONZE'
///   totalOrders 5-19  → 'SILVER'
///   totalOrders 20-49 → 'GOLD'
///   totalOrders 50+   → 'PLATINUM'
///
/// CONSTRAINTS:
///   - addresses array NEVER exceeds 5 items
///   - Only 1 address can have isDefault: true
///   - role NEVER changed by client — admin only via
///     Firebase Console or Cloud Function
///   - fcmToken is nullable (user may deny permissions)
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 2: /products/{productId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: All products, both active and archived
/// DOCUMENT ID: Auto-generated by Firestore
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   // ── Identity ──────────────────────────────────────
///   "productId":     String,   // = document ID (set after create)
///   "name":          String,   // min 3 chars
///   "brand":         String,   // e.g. 'LUXR MAISON'
///   "description":   String,   // rich text (markdown allowed)
///   "category":      String,   // ENUM (see categories below)
///   "subcategory":   String?,  // optional
///   "tags":          String[], // for search: ['silk','dress',...]
///
///   // ── Search optimization ───────────────────────────
///   "searchIndex":   String[], // lowercase tokens for search
///                              // generated on write:
///                              // split name+brand+tags by space
///                              // store as lowercase array
///
///   // ── Pricing ───────────────────────────────────────
///   "price":         double,   // original price, always > 0
///   "discountPct":   int,      // 0-90 (percent off)
///   "finalPrice":    double,   // COMPUTED: price*(1-discount/100)
///                              // stored for query performance
///
///   // ── Media ─────────────────────────────────────────
///   "imageUrls":     String[], // min 1, Firebase Storage URLs
///   "thumbnailUrl":  String,   // first image = thumbnail
///
///   // ── Inventory (MAP — key = size, value = qty) ─────
///   "inventory": {
///     "XS": int,   // stock count per size
///     "S":  int,
///     "M":  int,
///     "L":  int,
///     "XL": int,
///     "XXL": int,
///     "ONE_SIZE": int  // for accessories/bags
///   },
///   "totalStock":    int,      // SUM of all inventory values
///                              // CRITICAL: updated atomically
///   "lowStockThreshold": int,  // default 5, admin can override
///
///   // ── Colors ────────────────────────────────────────
///   "colors": [
///     {
///       "name":      String,   // 'Obsidian Black'
///       "hexCode":   String,   // '#1A1A1A'
///     }
///   ],
///
///   // ── Status flags ──────────────────────────────────
///   "isActive":      bool,     // false = soft deleted/archived
///   "isFeatured":    bool,     // shows on home Featured section
///   "isNewArrival":  bool,     // shows on New Arrivals section
///   "isLimitedEdition": bool,
///
///   // ── Analytics ─────────────────────────────────────
///   "avgRating":     double,   // 0.0 - 5.0
///   "reviewCount":   int,      // total reviews
///   "soldCount":     int,      // total units sold (all time)
///   "viewCount":     int,      // total product page views
///
///   // ── Timestamps ────────────────────────────────────
///   "createdAt":     Timestamp,
///   "updatedAt":     Timestamp,
///   "createdBy":     String    // admin uid
/// }
///
/// VALID CATEGORIES:
///   'Apparel' | 'Footwear' | 'Accessories' | 'Bags' |
///   'Watches' | 'Jewelry' | 'Beauty' | 'Winter Wear'
///
/// INVENTORY RULES:
///   - totalStock = XS+S+M+L+XL+XXL+ONE_SIZE (always)
///   - When ANY size hits 0: do NOT remove key, keep at 0
///   - totalStock 0 = OUT OF STOCK
///   - totalStock 1-lowStockThreshold = LOW STOCK
///   - totalStock > lowStockThreshold = IN STOCK
///   - Stock updates MUST use Firestore transactions
///   - finalPrice MUST be recomputed on every price/discount update
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 3: /orders/{orderId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: All customer orders
/// DOCUMENT ID: Custom format "SC-" + timestamp + random4
/// Example: "SC-1698123456-A7K2"
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   // ── Identity ──────────────────────────────────────
///   "orderId":       String,   // = document ID
///   "userId":        String,   // buyer's uid
///   "userEmail":     String,   // denormalized for admin queries
///   "userName":      String,   // denormalized
///
///   // ── Items (array of order items) ──────────────────
///   "items": [
///     {
///       "productId":   String,
///       "productName": String, // denormalized (snapshot)
///       "brand":       String, // denormalized
///       "imageUrl":    String, // first image
///       "size":        String,
///       "color":       String, // color name
///       "quantity":    int,    // >= 1
///       "unitPrice":   double, // price AT TIME OF ORDER
///       "discountPct": int,    // discount AT TIME OF ORDER
///       "finalPrice":  double, // unitPrice after discount
///       "lineTotal":   double  // finalPrice * quantity
///     }
///   ],
///
///   // ── Pricing Summary ───────────────────────────────
///   "subtotal":      double,   // sum of all lineTotals
///   "shippingCost":  double,   // 0 = free, 25 = express
///   "discountAmount":double,   // from promo codes (Phase 6)
///   "taxAmount":     double,   // 0 for MVP
///   "total":         double,   // subtotal+shipping-discount+tax
///
///   // ── Shipping ──────────────────────────────────────
///   "shippingMethod": String,  // 'standard' | 'express'
///   "shippingAddress": {       // SNAPSHOT of address at order time
///     "fullName":  String,
///     "phone":     String,
///     "street":    String,
///     "city":      String,
///     "state":     String,
///     "zipCode":   String,
///     "country":   String
///   },
///   "estimatedDelivery": {
///     "from":      Timestamp,
///     "to":        Timestamp
///   },
///
///   // ── Payment ───────────────────────────────────────
///   "paymentMethod": String,   // 'cod' | 'online'
///   "paymentStatus": String,   // 'pending'|'paid'|'refunded'
///   "transactionId": String?,  // from payment gateway
///
///   // ── Status & Timeline ─────────────────────────────
///   "status":        String,
///   // ENUM: 'pending'|'confirmed'|'processing'|
///   //       'packed'|'shipped'|'out_for_delivery'|
///   //       'delivered'|'cancelled'|'return_requested'|
///   //       'returned'
///
///   "statusHistory": [         // append-only log
///     {
///       "status":    String,
///       "timestamp": Timestamp,
///       "note":      String?,  // admin note
///       "updatedBy": String    // admin uid or 'system'
///     }
///   ],
///
///   // ── Courier (added when shipped) ──────────────────
///   "courier": {
///     "name":          String?,
///     "trackingNumber": String?,
///     "estimatedTime": String?  // "Today, 5:00 PM"
///   },
///
///   // ── Timestamps ────────────────────────────────────
///   "placedAt":      Timestamp, // FieldValue.serverTimestamp
///   "updatedAt":     Timestamp,
///   "deliveredAt":   Timestamp?
/// }
///
/// ORDER ID GENERATION:
///   String generateOrderId() {
///     final timestamp = DateTime.now()
///         .millisecondsSinceEpoch.toString()
///         .substring(7); // last 6 digits
///     final random = Random().nextInt(9999)
///         .toString().padLeft(4, '0');
///     return 'SC-$timestamp-$random'.toUpperCase();
///   }
///
/// CRITICAL RULES:
///   - Items array is a SNAPSHOT (never references products)
///   - Prices in items NEVER change after order placed
///   - statusHistory is APPEND-ONLY (never delete entries)
///   - Stock deduction happens in SAME transaction as
///     order document creation
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 4: /users/{uid}/cart/{cartItemId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: User's active cart (subcollection of user)
/// DOCUMENT ID: productId + "_" + size + "_" + colorName
/// Example: "abc123_M_ObsidianBlack"
/// (This prevents duplicate entries for same product+size+color)
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "cartItemId":    String,   // = document ID
///   "productId":     String,
///   "productName":   String,   // denormalized
///   "brand":         String,   // denormalized
///   "imageUrl":      String,   // thumbnail
///   "size":          String,
///   "color":         String,   // color name
///   "colorHex":      String,
///   "quantity":      int,      // >= 1
///   "unitPrice":     double,   // LIVE price (re-read on checkout)
///   "discountPct":   int,      // LIVE discount
///   "finalPrice":    double,   // COMPUTED
///   "addedAt":       Timestamp,
///   "updatedAt":     Timestamp
/// }
///
/// CART RULES:
///   - Max 20 items in cart
///   - If same productId+size+color added again:
///     INCREMENT quantity, don't add new doc
///   - Cart is NOT a reservation — stock is NOT held
///   - On checkout: re-validate prices from /products
///   - Cart survives logout (stored in Firestore, not memory)
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 5: /users/{uid}/wishlist/{productId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: User's saved/wishlisted products
/// DOCUMENT ID: productId (prevents duplicates)
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "productId":     String,   // = document ID
///   "productName":   String,   // denormalized
///   "brand":         String,
///   "imageUrl":      String,
///   "price":         double,
///   "discountPct":   int,
///   "finalPrice":    double,
///   "category":      String,
///   "addedAt":       Timestamp
/// }
///
/// WISHLIST RULES:
///   - Max 50 items
///   - Document ID = productId prevents double-wishlisting
///   - On add: increment users/{uid}.wishlistCount
///   - On remove: decrement users/{uid}.wishlistCount
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 6: /products/{productId}/reviews/{reviewId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: Product reviews and ratings (subcollection)
/// DOCUMENT ID: Auto-generated
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "reviewId":      String,   // = document ID
///   "userId":        String,
///   "userName":      String,   // denormalized
///   "userPhotoUrl":  String?,
///   "orderId":       String,   // MUST have purchased to review
///   "rating":        int,      // 1-5
///   "title":         String?,
///   "body":          String,   // min 10 chars
///   "isVerifiedPurchase": bool,// true if orderId valid
///   "helpfulCount":  int,      // upvotes
///   "createdAt":     Timestamp,
///   "isVisible":     bool      // admin can hide reviews
/// }
///
/// REVIEW RULES:
///   - 1 review per user per product (enforced by security rules)
///   - Must have orderId from a DELIVERED order
///   - On new review: update products/{id}.avgRating
///     and reviewCount via Cloud Function (or transaction)
///   - avgRating = sum(all ratings) / reviewCount
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 7: /categories/{categoryId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: Product categories with metadata
/// DOCUMENT ID: slug (e.g., 'apparel', 'footwear')
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "categoryId":    String,   // = document ID (slug)
///   "name":          String,   // display name
///   "iconUrl":       String?,  // Firebase Storage icon
///   "bannerUrl":     String?,  // category page banner
///   "productCount":  int,      // maintained by Cloud Function
///   "sortOrder":     int,      // display order in UI
///   "isActive":      bool,
///   "createdAt":     Timestamp
/// }
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 8: /banners/{bannerId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: Home screen promotional banners
/// DOCUMENT ID: Auto-generated
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "bannerId":      String,
///   "title":         String,   // e.g. "Winter Collection '24"
///   "subtitle":      String?,
///   "imageUrl":      String,   // Full-width hero image
///   "actionLabel":   String,   // "SHOP NOW"
///   "actionRoute":   String,   // deep link route
///   "sortOrder":     int,
///   "isActive":      bool,
///   "startDate":     Timestamp?,// null = always active
///   "endDate":       Timestamp?,// null = always active
///   "createdAt":     Timestamp
/// }
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 9: /notifications/{notificationId}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: In-app notification history per user
/// DOCUMENT ID: Auto-generated
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "notificationId": String,
///   "userId":         String,  // target user uid
///   "title":          String,
///   "body":           String,
///   "type":           String,
///   // ENUM: 'order_update'|'promotion'|'new_arrival'|'system'
///   "data": {                  // extra payload for deep link
///     "orderId":      String?,
///     "productId":    String?,
///     "route":        String?
///   },
///   "isRead":         bool,    // default false
///   "createdAt":      Timestamp
/// }
///
/// ══════════════════════════════════════════════════════════
/// COLLECTION 10: /analytics/{dateKey}
/// ══════════════════════════════════════════════════════════
/// PURPOSE: Daily aggregated analytics (written by Cloud Functions)
/// DOCUMENT ID: Date string "YYYY-MM-DD"
///
/// FULL DOCUMENT STRUCTURE:
/// {
///   "date":           String,  // "2024-10-24"
///   "revenue":        double,  // total revenue that day
///   "orderCount":     int,
///   "newCustomers":   int,
///   "cancelledOrders":int,
///   "topProducts": [           // top 5 by soldCount that day
///     {
///       "productId":  String,
///       "name":       String,
///       "unitsSold":  int,
///       "revenue":    double
///     }
///   ],
///   "revenueByCategory": {     // map of category → revenue
///     "Apparel":      double,
///     "Footwear":     double,
///     // ...
///   },
///   "avgOrderValue":  double,
///   "conversionRate": double,  // orders / sessions (from Analytics)
///   "updatedAt":      Timestamp
/// }
///
/// ══════════════════════════════════════════════════════════
/// FIRESTORE INDEXES — Create ALL of these in Firebase Console
/// ══════════════════════════════════════════════════════════
///
/// PRODUCTS collection:
///   1. category ASC + isActive ASC + createdAt DESC
///      (category page, newest first)
///   2. isFeatured ASC + isActive ASC + createdAt DESC
///      (home featured section)
///   3. isNewArrival ASC + isActive ASC + createdAt DESC
///      (new arrivals section)
///   4. category ASC + finalPrice ASC + isActive ASC
///      (price sort ascending)
///   5. category ASC + finalPrice DESC + isActive ASC
///      (price sort descending)
///   6. category ASC + avgRating DESC + isActive ASC
///      (sort by rating)
///   7. isActive ASC + soldCount DESC
///      (best sellers)
///   8. tags ARRAY_CONTAINS + isActive ASC
///      (tag-based filtering)
///   9. searchIndex ARRAY_CONTAINS + isActive ASC
///      (search)
///   10. totalStock ASC + isActive ASC
///       (low stock admin view)
///
/// ORDERS collection:
///   1. userId ASC + placedAt DESC
///      (my orders screen)
///   2. status ASC + placedAt DESC
///      (admin filter by status)
///   3. userId ASC + status ASC + placedAt DESC
///      (customer filtered orders)
///   4. placedAt DESC
///      (admin all orders by date)
///
/// NOTIFICATIONS collection:
///   1. userId ASC + isRead ASC + createdAt DESC
///      (unread notifications)
///   2. userId ASC + createdAt DESC
///      (all notifications)
///
/// ANALYTICS collection:
///   1. date DESC
///      (most recent analytics first)

class UserFields {
  static const String emailVerified = 'emailVerified';

  // Addresses embedded array fields
  static const String addressId = 'addressId';
  static const String label = 'label';
  static const String fullName = 'fullName';
  static const String phone = 'phone';
  static const String street = 'street';
  static const String city = 'city';
  static const String state = 'state';
  static const String zipCode = 'zipCode';
  static const String country = 'country';
  static const String isDefault = 'isDefault';

  // Notification Preferences fields
  static const String orderUpdates = 'orderUpdates';
  static const String promotions = 'promotions';
  static const String newArrivals = 'newArrivals';
}

class ProductFields {
  static const String productId = 'productId';
  static const String description = 'description';
  static const String subcategory = 'subcategory';
  static const String finalPrice = 'finalPrice';
  static const String thumbnailUrl = 'thumbnailUrl';
  static const String lowStockThreshold = 'lowStockThreshold';
  static const String colors = 'colors';
  static const String isActive = 'isActive';
  static const String isLimitedEdition = 'isLimitedEdition';
  static const String viewCount = 'viewCount';
  static const String updatedAt = 'updatedAt';
  static const String createdBy = 'createdBy';
  static const String createdAt = 'createdAt';

  // Color subfields
  static const String colorName = 'name';
  static const String hexCode = 'hexCode';
}

class OrderFields {
  static const String userEmail = 'userEmail';
  static const String userName = 'userName';
  static const String taxAmount = 'taxAmount';
  static const String discountAmount = 'discountAmount';
  static const String shippingMethod = 'shippingMethod';
  static const String shippingAddress = 'shippingAddress';
  static const String paymentStatus = 'paymentStatus';
  static const String transactionId = 'transactionId';
  static const String courier = 'courier';
  static const String deliveredAt = 'deliveredAt';

  // Order Item subfields
  static const String productId = 'productId';
  static const String productName = 'productName';
  static const String brand = 'brand';
  static const String imageUrl = 'imageUrl';
  static const String size = 'size';
  static const String color = 'color';
  static const String quantity = 'quantity';
  static const String unitPrice = 'unitPrice';
  static const String discountPct = 'discountPct';
  static const String finalPrice = 'finalPrice';
  static const String lineTotal = 'lineTotal';

  // Courier subfields
  static const String courierName = 'name';
  static const String trackingNumber = 'trackingNumber';
  static const String estimatedTime = 'estimatedTime';

  // Status History subfields
  static const String timestamp = 'timestamp';
  static const String note = 'note';
  static const String updatedBy = 'updatedBy';

  // Estimated Delivery subfields
  static const String from = 'from';
  static const String to = 'to';
}

class CartItemFields {
  static const String cartItemId = 'cartItemId';
  static const String productId = 'productId';
  static const String productName = 'productName';
  static const String brand = 'brand';
  static const String imageUrl = 'imageUrl';
  static const String size = 'size';
  static const String color = 'color';
  static const String colorHex = 'colorHex';
  static const String quantity = 'quantity';
  static const String unitPrice = 'unitPrice';
  static const String discountPct = 'discountPct';
  static const String finalPrice = 'finalPrice';
  static const String addedAt = 'addedAt';
  static const String updatedAt = 'updatedAt';
}

class WishlistItemFields {
  static const String productId = 'productId';
  static const String productName = 'productName';
  static const String brand = 'brand';
  static const String imageUrl = 'imageUrl';
  static const String price = 'price';
  static const String discountPct = 'discountPct';
  static const String finalPrice = 'finalPrice';
  static const String category = 'category';
  static const String addedAt = 'addedAt';
}

class ReviewFields {
  static const String reviewId = 'reviewId';
  static const String userId = 'userId';
  static const String userName = 'userName';
  static const String userPhotoUrl = 'userPhotoUrl';
  static const String orderId = 'orderId';
  static const String rating = 'rating';
  static const String title = 'title';
  static const String body = 'body';
  static const String isVerifiedPurchase = 'isVerifiedPurchase';
  static const String helpfulCount = 'helpfulCount';
  static const String createdAt = 'createdAt';
  static const String isVisible = 'isVisible';
}

class CategoryFields {
  static const String categoryId = 'categoryId';
  static const String name = 'name';
  static const String iconUrl = 'iconUrl';
  static const String bannerUrl = 'bannerUrl';
  static const String productCount = 'productCount';
  static const String sortOrder = 'sortOrder';
  static const String isActive = 'isActive';
  static const String createdAt = 'createdAt';
}

class BannerFields {
  static const String bannerId = 'bannerId';
  static const String title = 'title';
  static const String subtitle = 'subtitle';
  static const String imageUrl = 'imageUrl';
  static const String actionLabel = 'actionLabel';
  static const String actionRoute = 'actionRoute';
  static const String sortOrder = 'sortOrder';
  static const String isActive = 'isActive';
  static const String startDate = 'startDate';
  static const String endDate = 'endDate';
  static const String createdAt = 'createdAt';
}

class NotificationFields {
  static const String notificationId = 'notificationId';
  static const String userId = 'userId';
  static const String title = 'title';
  static const String body = 'body';
  static const String type = 'type';
  static const String data = 'data';
  static const String isRead = 'isRead';
  static const String createdAt = 'createdAt';

  // Data payload subfields
  static const String orderId = 'orderId';
  static const String productId = 'productId';
  static const String route = 'route';
}

class AnalyticsFields {
  static const String date = 'date';
  static const String revenue = 'revenue';
  static const String orderCount = 'orderCount';
  static const String newCustomers = 'newCustomers';
  static const String cancelledOrders = 'cancelledOrders';
  static const String topProducts = 'topProducts';
  static const String revenueByCategory = 'revenueByCategory';
  static const String avgOrderValue = 'avgOrderValue';
  static const String conversionRate = 'conversionRate';
  static const String updatedAt = 'updatedAt';

  // Top Products subfields
  static const String productId = 'productId';
  static const String name = 'name';
  static const String unitsSold = 'unitsSold';
  // revenue is already defined above
}

class OrderStatus {
  static const String pending = 'pending';
  static const String confirmed = 'confirmed';
  static const String processing = 'processing';
  static const String packed = 'packed';
  static const String shipped = 'shipped';
  static const String outForDelivery = 'out_for_delivery';
  static const String delivered = 'delivered';
  static const String cancelled = 'cancelled';
  static const String returnRequested = 'return_requested';
  static const String returned = 'returned';
}

class PaymentMethod {
  static const String cod = 'cod';
  static const String online = 'online';
}

class PaymentStatus {
  static const String pending = 'pending';
  static const String paid = 'paid';
  static const String refunded = 'refunded';
}

class ShippingMethod {
  static const String standard = 'standard';
  static const String express = 'express';
}

class NotificationType {
  static const String orderUpdate = 'order_update';
  static const String promotion = 'promotion';
  static const String newArrival = 'new_arrival';
  static const String system = 'system';
}

class EliteStatus {
  static const String bronze = 'BRONZE';
  static const String silver = 'SILVER';
  static const String gold = 'GOLD';
  static const String platinum = 'PLATINUM';
}

class ProductCategory {
  static const String apparel = 'Apparel';
  static const String footwear = 'Footwear';
  static const String accessories = 'Accessories';
  static const String bags = 'Bags';
  static const String watches = 'Watches';
  static const String jewelry = 'Jewelry';
  static const String beauty = 'Beauty';
  static const String winterWear = 'Winter Wear';
  static const String outerwear = 'Outerwear';
  static const String shirts = 'Shirts';
  static const String hoodies = 'Hoodies';

  static const List<String> all = [
    apparel,
    footwear,
    accessories,
    bags,
    watches,
    jewelry,
    beauty,
    winterWear,
    outerwear,
    shirts,
    hoodies,
  ];
}

class ProductSize {
  static const String xs = 'XS';
  static const String s = 'S';
  static const String m = 'M';
  static const String l = 'L';
  static const String xl = 'XL';
  static const String xxl = 'XXL';
  static const String oneSize = 'ONE_SIZE';

  static const List<String> all = [xs, s, m, l, xl, xxl, oneSize];
  static const List<String> accessories = [oneSize];
}
